### ISSUE TITLE
Failure when following quickstart

### ISSUE THREAD

**Issue by heralden** [intermine/docker-intermine-gradle#7]
I tried to follow the *Quickstart* in the README and I'm unable to start a biotestmine instance when running `docker-compose -f local.docker-compose.yml up --build --force-recreate` or `docker-compose -f dockerhub.docker-compose.yml up`. Here's the error I get when running the latter command.

```
intermine_builder    | FAILURE: Build failed with an exception.
intermine_builder    | 
intermine_builder    | * What went wrong:
intermine_builder    | Execution failed for task ':dbmodel:retrieveSingleSource'.
intermine_builder    | > dataDir is not a directory:uniprot
intermine_builder    | 
intermine_builder    | * Try:
intermine_builder    | Run with --info or --debug option to get more log output. Run with --scan to get full insights.
intermine_builder    | 
intermine_builder    | * Exception is:
intermine_builder    | org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':dbmodel:retrieveSingleSource'.
intermine_builder    | 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
intermine_builder    | 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
intermine_builder    | 	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
intermine_builder    | 	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
intermine_builder    | 	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
intermine_builder    | 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
intermine_builder    | 	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
intermine_builder    | 	at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
intermine_builder    | 	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
intermine_builder    | 	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
intermine_builder    | 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
intermine_builder    | 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
intermine_builder    | 	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
intermine_builder    | 	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
intermine_builder    | 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
intermine_builder    | 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
intermine_builder    | 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
intermine_builder    | 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
intermine_builder    | 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
intermine_builder    | 	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
intermine_builder    | 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
intermine_builder    | 	at org.gradle.execution.taskgraph.LocalTaskInfoExecutor.execute(LocalTaskInfoExecutor.java:42)
intermine_builder    | 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:273)
intermine_builder    | 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:258)
intermine_builder    | 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
intermine_builder    | 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
intermine_builder    | 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
intermine_builder    | 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
intermine_builder    | 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
intermine_builder    | 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
intermine_builder    | 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
intermine_builder    | 	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
intermine_builder    | Caused by: : dataDir is not a directory:uniprot
intermine_builder    | 	at org.intermine.task.DirectoryConverterTask.execute(DirectoryConverterTask.java:63)
intermine_builder    | 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
intermine_builder    | 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
intermine_builder    | 	at org.intermine.plugin.integrate.IntegrateUtils$_closure5.doCall(IntegrateUtils.groovy:128)
intermine_builder    | 	at org.intermine.plugin.integrate.IntegrateUtils.invokeMethod(IntegrateUtils.groovy)
intermine_builder    | 	at org.intermine.plugin.integrate.IntegrateUtils$_closure2.doCall(IntegrateUtils.groovy:51)
intermine_builder    | 	at org.intermine.plugin.integrate.IntegratePlugin$_apply_closure7$_closure20.doCall(IntegratePlugin.groovy:179)
intermine_builder    | 	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:724)
intermine_builder    | 	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:697)
intermine_builder    | 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
intermine_builder    | 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
intermine_builder    | 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
intermine_builder    | 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
intermine_builder    | 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
intermine_builder    | 	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
intermine_builder    | 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
intermine_builder    | 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
intermine_builder    | 	... 31 more
intermine_builder    | 
intermine_builder    | 
intermine_builder    | * Get more help at https://help.gradle.org
intermine_builder    | 
intermine_builder    | BUILD FAILED in 7s
intermine_builder    | Fri Dec  6 10:28:53 UTC 2019
intermine_builder    | 
intermine_builder    | finished
intermine_builder    | 
intermine_builder    | 
intermine_builder    | ERROR: 256
intermine_builder    | failed with exit code 0: /home/intermine/intermine/biotestmine/gradlew --stacktrace --no-daemon integrate -Psource=uniprot-malaria
intermine_builder    | 
intermine_builder    | check log: pbuild.log
intermine_builder exited with code 1
```

@leoank Do you have a chance to look at this?

Note: I haven't done any setup other than installing docker and docker-compose and starting the docker daemon, so let me know if I've missed anything.

**Comment by leoank** [comment]
I tried to reproduce your error. But, `local.docker-compose.yml` worked for me. `intermine builder exited with code 0`. Make sure you have no `.env` file in root of the repo or everything is in comments in `.env` file. Also, can you verify that this line `- ./data/mine/data:/home/intermine/intermine/data` in the `intermine_builder` section (line 8) is in comments?

`dockerhub.docker-compose.yml` gave me the same error as yours.  Fixed this issue in the last commit.

However, I don't know why tomcat is not working. War is deployed without errors but tomcat is giving 404 when trying to access biotestmine at `localhost:9999/biotestmine`. But, biotestmine is listed in the deployed applications list. You can check the server status using the default credentials(user=alice, pass=whatever)

@yochannah @danielabutano Is something changed with the webapp deployment process in the new version of intermine? Can you help with verifying tomcat configs? They are located in the `tomcat/configs` directory.

**Comment by heralden** [comment]
Thanks for the quick reply!

`dockerhub.docker-compose.yml` completes successfully now after pulling your commit.

`local.docker-compose.yml` probably also completed successfully when I tested it, but like you mentioned, it returns 404 so I must have thought it failed to build as well. (I also verified I had no `.env` and that the line was commented out.)

I have experienced that after the Gradle version update, I've had to `--stop` before running `tomcatStartWar` again (https://github.com/intermine/ci-scripts/pull/6). Not sure if this is related, but I'm going to try it inside the docker containers spawned by compose and see if it helps.

**Comment by heralden** [comment]
I finally managed to figure out how to do this with docker-compose: (where `ba58` is my `intermine/builder` container ID).

```
sudo docker commit ba58 user/builder_image
sudo docker run --network=docker-intermine-gradle_default -ti --entrypoint=sh user/builder_image
cd biotestmine/
./gradlew cargoRedeployRemote
```

Running `cargoRedeployRemote` a second time fixes it, as now http://localhost:9999/biotestmine/ opens the biotestmine webapp as expected.

It seems like something is very fishy with the new biotestmine war!

**Comment by leoank** [comment]
Fixed it by changing the `build.sh` script in intermine_builder folder to use your workaround. Can you verify that it is working for you now?

**Comment by leoank** [comment]
And yes! something is wrong with the biotestmine war. More debugging is needed to permanently fix this issue. 
- `cargoDeployRemote` command is not working on first try, but a biotesmine app can be seen in the application list on tomcat server
- `tomcatStartWar` command is not working. biotestmine app is not listed in the application list on tomcat server

**Comment by heralden** [comment]
Yes, the change does work. Is it correct to assume we'll need to update the image/dockerfile on dockerhub as well?

Thanks for the help. I'll close the issue now.

I spoke with @danielabutano and created https://github.com/intermine/intermine/issues/2162. She should check out the biotestmine problem soon.

**Comment by leoank** [comment]
yes. intermine_builder image on dockerhub needs to be updated too. However, I did that before pushing the commit upstream. It will be good to have a CI job to that automatically on every commit. Thanks for checking out the repo and giving feedback!
